### ISSUE TITLE
Add support for LinearRing outside Polygon

### ISSUE THREAD

**Issue by mbloch** [placemark/togeojson#104]
This converter seems not to import KML `<LinearRing>` geometries that are nested directly within a `<Placemark>` (as opposed to being contained within a `<Polygon>`). I'm attaching an example kmz from NOAA that uses a `<LinearRing>` as a bounding box. `togeojson` and Placemark.io import placemark as a feature with null geometry. Importing as a GeoJSON `LineString` makes sense to me.

[Archive.zip](https://github.com/placemark/togeojson/files/10271919/Archive.zip)

**Comment by tmcw** [comment]
Hey Matt - totally, that makes sense. Didn't realize that LineStrings could be directly nested. I'll look into it.
