### ISSUE TITLE
GPX conversion adds "s" character to extension names

### ISSUE THREAD

**Issue by MI-KY** [placemark/togeojson#107]
Hi,

I actually searched for hours why I was not able to visualize some simple .gpx file with https://raruto.github.io/leaflet-elevation/.
My file looks like this:

```
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<gpx creator="test" version="1.1">
<metadata>
  <time>2023-02-04 12:00:00Z</time>
 </metadata>
 <trk>
    <name>Demo</name>
    <trkseg>
        <trkpt lat="43.6239918" lon="10.8706823">
                <ele>48.0</ele>
                <time>2023-02-04 12:00:00Z</time>
                <extensions>
                        <tempTireFRI>123</tempTireFRI>
                </extensions>
        </trkpt>
        <trkpt lat="43.6239920" lon="10.7706821">
                <ele>48.0</ele>
                <time>2023-02-04 12:00:00Z</time>
                <extensions>
                        <tempTireFRI>50.5</tempTireFRI>
                </extensions>
        </trkpt>
    </trkseg>
  </trk>
</gpx>
```

The problem was, that I've never been able to visualize the data inside leaflet-elevation until I looked into the code of gpx.ts. There I saw, that this line below always adds an "s" to the name of the element inside "extensions":
https://github.com/placemark/togeojson/blob/9eca1937cc5acc2d7faecb6ef8fa5c5ad182eb9b/lib/gpx.ts#L32

I'm not quite sure if this is done by error or maybe some standard I do not know (I'm pretty new to gpx / geojson).

**Comment by tmcw** [comment]
Yes, this is intentional. GPX stores data on each individual vertex of a line. KML doesn't have a way to represent data on vertices, only on the line. So togeojson combines the values of per-vertex datapoints into single properties, which means that the properties are named plural, because they contain multiple values.
