### ISSUE TITLE
KML Bounds Not Parsed

### ISSUE THREAD

**Issue by mackswell13** [placemark/togeojson#112]
When trying to parse the below kml that uses bounds rather than coordinates there is no way to access the north south east west bounds. I was hoping that this could be a added feature for those that are trying to access those bounds after parsing.

**Comment by mackswell13** [comment]
By bad.... This should be the correct one here can you remove that comment thanks!
[03 test.zip](https://github.com/placemark/togeojson/files/11802193/03.test.zip)

**Comment by tmcw** [comment]
Okay - so got it, this does contain bounds, which are parsed into Polygons. The idea is to produce a bbox property?

**Comment by mackswell13** [comment]
Yes a Bbox property would work great here. That would allow us to pull out the bbox object and pass as our bounds.
