### ISSUE TITLE
KMZ overlay with rotation not working correctly

### ISSUE THREAD

**Issue by jsk01** [placemark/togeojson#119]
I have a mapbox map that contains a KMZ file that displays some overlays correctly and others rotated incorrectly.  Further inspection shows all the overlays with rotation set to zero display correctly.  If rotation is set the rotation displayed on the map is off and inverted I believe.

Screenshot shows an overlay with rotation set as 41.0118 in Google Earth.  Changing the value to -41.0118 causes the image to be close to correct.  Although its still slightly off from the green outline polygon.  I have a version of the map using ESRI and it loads the KMZ correctly so I believe the issue is with togeojson logic in some way.
![issue with overlay rotation](https://github.com/placemark/togeojson/assets/7489721/23c20f51-1e75-43ba-a5e5-f678a6767998)

**Comment by tmcw** [comment]
https://github.com/placemark/togeojson/blob/578fdb52e2bab47ce4f5908fbdf9739eef19ed5d/lib/kml/ground_overlay.ts#L42

Currently togeojson handles rotations for GroundOverlays, but does not handle rotation for objects - assuming that this is a KML feature with a rotation property (a data example would be useful). I'm not currently seeing [anything in the KML reference](https://developers.google.com/kml/documentation/kmlreference) that indicates that any other geometry type could be rotated.

**Comment by jsk01** [comment]
Here's the kmz I'm having an issue with.  Only two overlays.  One with no rotation and one with rotation.

Legend Point is the overlay not rotating as expected.
Let me know if you don't have the same experience.  

Looking at the code above, line 52 should be plus rotation?  It would fit what I tested yesterday by making the rotation value a negative number in the kmz.

[Overlay1-test.zip](https://github.com/placemark/togeojson/files/12321162/Overlay1-test.zip)
