### ISSUE TITLE
TypeScript types

### ISSUE THREAD

**Issue by tmcw** [placemark/togeojson#46]
Should be pretty doable and helpful here.

**Comment by ElijahKotyluk** [comment]
Any updates on this? Willing to give a hand if need be.

**Comment by kachkaev** [comment]
@ElijahKotyluk feel free to! Happy to test them before the release 🙌

**Comment by tmcw** [comment]
I took a shot at trying to just port the whole thing over to TypeScript and… doesn't seem worth it right now, it'd be a ton of code change for little benefit. Clearing my assignee - if anyone wants to add types, go for it!

**Comment by TylerEich** [comment]
I wrote some incomplete TS declarations that suited what I needed for my usage. Maybe these can help someone else too
```typescript
import {
  Feature,
  FeatureCollection,
  GeoJsonObject,
  GeoJsonProperties,
  GeoJsonTypes,
  Geometry,
} from "geojson";

declare module "@tmcw/togeojson" {
  export function kml(doc: Document): FeatureCollection;

  export function kml<TProperties extends GeoJsonProperties>(
    doc: Document
  ): FeatureCollection<Geometry, TProperties>;

  export function* kmlGen(doc: Document): Generator<Feature, void, boolean>;
  export function* kmlGen<TProperties extends GeoJsonProperties>(
    doc: Document
  ): Generator<Feature<Geometry, TProperties>, void, boolean>;

  export function gpx(doc: Document): FeatureCollection;
  export function gpx<TProperties extends GeoJsonProperties>(
    doc: Document
  ): FeatureCollection<TProperties>;

  export function* gpxGen(doc: Document): Generator<Feature, void, boolean>;
  export function* gpxGen<TProperties extends GeoJsonProperties>(
    doc: Document
  ): Generator<Feature<Geometry, TProperties>, void, boolean>;

  export function tcx(doc: Document): FeatureCollection;
  export function tcx<TProperties extends GeoJsonProperties>(
    doc: Document
  ): FeatureCollection<Geometry, GeoJsonProperties>;
}
```

**Comment by juandelgado** [comment]
It's not going to work for everyone, but my use case requires using this library in a Node environment as part of script written in TypeScript. Since there are no types available I installed the [togeojson CLI](tmcw/togeojson-cli) and called it as a child process through Node's `exec`. Then feed the output of the CLI to `JSON.parse`. 

It's not pretty but gets the job done. For now at least.

Hope it helps.

**Comment by HansBrende** [comment]
@juandelgado 
```typescript
// @ts-ignore
import { kml } from "@tmcw/togeojson";
```

**Comment by tmcw** [comment]
The 5.x work in master includes typescript types in main. Going to integrate it into my application to kick the tires then we'll be good to go.

**Comment by tmcw** [comment]
The 5.0.0 release is out and includes TypeScript types!
