### ISSUE TITLE
Add GML to GeoJSON?

### ISSUE THREAD

**Issue by gg187on** [placemark/togeojson#49]

**Comment by tmcw** [comment]
I'm not sure. I'd consider a PR that partially converted from one to the other, but GML is a sprawling format and a comprehensive converter would be too large for a project like toGeoJSON (we don't want to include proj4, for example, to reproject coordinates).

**Comment by tmcw** [comment]
Yeah, I can't commit to GML support. The [standard is just nuts](http://erouault.blogspot.com/2014/04/gml-madness.html), the OGC made it impossible to support.
