### ISSUE TITLE
Which babel loader required to import KML

### ISSUE THREAD

**Issue by AzadAnsari35** [placemark/togeojson#83]
While importing the kml, 
import { kml } from '@tmcw/togeojson';

I am getting the below error. Any idea what loader it's required? I have been looking it for yesterday, but no luck.

ERROR in ./node_modules/@tmcw/togeojson/dist/togeojson.umd.js 1:366
Module parse failed: Unexpected token (1:366)        
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file.

This is how my webpack rules looks like.

`  rules: [
                {
                    test: /\.(js|jsx)$/,
                    exclude: /node_modules/,
                    use: 'babel-loader'
                },
                {
                    test: /\.(css|scss)$/,
                    use: [envType == 'prod' ? MiniCssExtractPlugin.loader : "style-loader",
                        "css-loader",
                        "sass-loader"
                    ]
                },
                {
                    test: /\.(jpg|jpeg|png|gif|mp3|svg|ico)$/,
                    loader: ['file-loader']
                },
                {
                    test: /\.(woff(2)?|ttf|eot)(\?v=\d+\.\d+\.\d+)?$/,
                    use: [
                        {
                            loader: 'file-loader',
                            options: {
                                name: '[name].[ext]',
                                outputPath: 'fonts/'
                            }
                        }
                    ]
                }
            ]`

**Comment by tmcw** [comment]
Okay, it looks like this error is happening because you're using Webpack 4, and toGeoJSON uses optional chaining syntax which is not supported by that version, but is supported by Webpack 5.

I think the target for this package should continue to be es2020 or so, in which optional chaining is a JavaScript feature - and that's supported by 90% of [current internet users](https://caniuse.com/mdn-javascript_operators_optional_chaining). Would it be possible to update to Webpack 5, or include togeojson in babel-loader configuration?

**Comment by AzadAnsari35** [comment]
Yes, we are using webpack 4. I think we can't update to webpack 5 as the product is old and updating will cause unexpected errors and we are very tight on deadlines now. Is there any other solution? Like can I add optional chaining loader in babel to fix this?

**Comment by tmcw** [comment]
Yep, if you're using preset-env, it should include the optional chaining plugin. If not, you can use https://babeljs.io/docs/en/babel-plugin-proposal-optional-chaining .
