### ISSUE TITLE
gpx() and kml() types aren't symmetric

### ISSUE THREAD

**Issue by jaybo** [placemark/togeojson#84]
**gpx**
```
gpx(node: Document): FeatureCollection<Geometry, GeoJsonProperties>
```
**kml**
```
kml(node: Document): FeatureCollection<Geometry | null, GeoJsonProperties>  // note the null
```
Which means I need to write 2 more lines of code.  Trivial, YES! (But it did break my build).

**Comment by tmcw** [comment]
These types are correct. KML features can lack geometries but have data. Features with null geometries are valid in KML and GeoJSON, but not something that GPX can contain.

**Comment by tmcw** [comment]
Closing - this is a bit annoying, but there's no way for the two have the same type signatures - you can expand the type for gpx to that of kml if you need a single function handle both.
