### ISSUE TITLE
Unable to use ESM import

### ISSUE THREAD

**Issue by neave** [placemark/togeojson#86]
I'm seeing errors when importing the module into an ESM project:
```
import { kml } from '@tmcw/togeojson';
         ^^^
SyntaxError: Named export 'kml' not found. The requested module '@tmcw/togeojson' is a CommonJS module, which may not support all module.exports as named exports.
```

But if I use this method:
```
import toGeoJSON from '@tmcw/togeojson';
```

I see this error:

```
export { gpx, gpxGen, kml, kmlGen, kmlWithFolders, tcx, tcxGen };
^^^^^^

SyntaxError: Unexpected token 'export'
```

So I'm kinda stuck. Any idea what's happening here? Using v5.1.2

**Comment by rkaravia** [comment]
The error seems to happen when using native (meaning without bundler) ES modules in node.

## Reproducing the error

To reproduce this, `npm install @tmcw/togeojson`, then create a file `test.mjs` with this content:

```js
import toGeoJSON from '@tmcw/togeojson';
```

Alternatively, you can also name the file `test.js`, and add `"type": "module"` to the `package.json` that has `@tmcw/togeojson` as a dependency.

## Fixing it

The fix seems to be to also add `"type": "module"` to togeojson's package.json, see also [npm docs about "type"](https://nodejs.org/api/packages.html#type).

**Comment by neave** [comment]
Here's a very basic set up. No bundlers. I'm on a Mac using Node v16.13.2, npm v8.5.5.
```
mkdir test
cd test
npm init
# enter to all
nano package.json
# add "type": "module",
npm i @tmcw/togeojson
nano test.js
# add the following:
import { kml } from '@tmcw/togeojson';
console.log(kml);
# save, exit
node test.js
```

Then I see the first error `Named export 'kml' not found.` etc. about it being CommonJS. Second method:
```
nano test.js
# amend the import to the following:
import toGeoJSON from '@tmcw/togeojson';
```

And then I see the second error.

**Comment by neave** [comment]
> The fix seems to be to also add `"type": "module"` to togeojson's package.json

Yes that could fix this issue, but based on https://github.com/placemark/togeojson/issues/63#issuecomment-1061252314 it may not be that simple:

> Okay, it was the `type: "module"` field, which opens a real can of worms. Introduced 4.6.1, which renames `main` to `.cjs` and adds an `export` field in package.json to direct users to that.

**Comment by tmcw** [comment]
v5.1.3 released with a fix. Changing file endings for the export from `.js` to `.mjs` enables Node.js native ESM support without changing everything else. Thanks for the bug report!
